# Generated by Django 3.0.7 on 2020-09-02 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='medCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryEN', models.CharField(max_length=50)),
                ('categoryAR', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalName', models.CharField(max_length=100)),
                ('arabicName', models.CharField(max_length=100, null=True)),
                ('scientificName', models.CharField(default='', max_length=100)),
                ('manufactureCompanyAr', models.CharField(max_length=50)),
                ('manufactureCompanyEn', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, default='profile.png', null=True, upload_to='medicine/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medCategory')),
            ],
        ),
        migrations.CreateModel(
            name='medType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeEN', models.CharField(max_length=50)),
                ('typeAR', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accType', models.CharField(choices=[('no', 'عادي'), ('ph', 'صيدلية'), ('or', 'مبادرة')], default='no', max_length=3)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('is_Available', models.BooleanField(default=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='requestMedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineGeneral', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, default='profile.png', null=True, upload_to='medicine/request/new/')),
                ('description', models.TextField(blank=True, null=True)),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('request', 'طلب'), ('donate', 'تبرع')], max_length=20)),
                ('prescription', models.ImageField(blank=True, null=True, upload_to='medicine/request/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacyAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyName', models.CharField(blank=True, max_length=100, null=True)),
                ('facebookPage', models.URLField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('whatsappNumber', models.BigIntegerField(blank=True, null=True)),
                ('licenseImg', models.ImageField(upload_to='license/')),
                ('licenseNumber', models.CharField(max_length=30)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='organizationAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookPage', models.URLField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('whatsappNumber', models.BigIntegerField(blank=True, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medType'),
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('locUrl', models.URLField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
