# Generated by Django 3.0.7 on 2020-08-01 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medCategory',
        ),
        migrations.DeleteModel(
            name='medType',
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[('tablet', 'حبوب'), ('capsule', 'كبسولات'), ('syrup', 'شراب'), ('injection', 'حقن'), ('nasalDrops', 'قطرة أنف'), ('nasalSpray', 'بخاخ أنف'), ('eyeDrops', 'قطرة عين'), ('cream', 'كريم'), ('gel', 'جيل'), ('pen', 'قلم'), ('eyeOint', 'مرهم عين'), ('earDrops', 'قطرة أذن')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
