# Generated by Django 2.2.7 on 2020-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(default='profile/profile.png', upload_to='profile/'),
        ),
    ]
