# Generated by Django 3.0.7 on 2020-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20200623_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='img',
            field=models.ImageField(default='', upload_to='medicine/static/medicine/img/profile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(upload_to='medicine/static/medicine/img/'),
        ),
    ]
