# Generated by Django 3.1.1 on 2020-09-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20200904_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medcategory'),
        ),
    ]
