# Generated by Django 2.2.7 on 2020-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20200627_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(default='profile/profile.png', null=True, upload_to='profile/'),
        ),
    ]
