# Generated by Django 2.2.7 on 2020-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20200627_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(blank=True, default='profile/profile.png', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
