# Generated by Django 3.0.7 on 2020-08-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20200801_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='username',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.medCategory'),
            preserve_default=False,
        ),
    ]
