# Generated by Django 3.1.1 on 2020-09-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationacc',
            name='organizationName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyacc',
            name='pharmacyName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
