# Generated by Django 3.0.7 on 2020-06-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20200624_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(upload_to='medicine/static/medicine/img/medicine'),
        ),
    ]
