# Generated by Django 2.2.7 on 2020-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20200627_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='quantity',
        ),
        migrations.AddField(
            model_name='user_info',
            name='facebookPage',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='pharmacyName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(blank=True, default='media/profile/profile.png', null=True, upload_to='medicine/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='scientificName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
