# Generated by Django 3.0.7 on 2020-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20200803_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medcategory',
            old_name='category',
            new_name='categoryAR',
        ),
        migrations.RenameField(
            model_name='medtype',
            old_name='type',
            new_name='typeAR',
        ),
        migrations.AddField(
            model_name='medcategory',
            name='categoryEN',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medtype',
            name='typeEN',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmedi',
            name='type',
            field=models.CharField(choices=[('request', 'طلب'), ('donate', 'تبرع')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
