# Generated by Django 3.1.1 on 2020-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20200904_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='originCountry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='scientificName',
            field=models.CharField(max_length=100),
        ),
    ]
