# Generated by Django 3.0.7 on 2020-06-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_medicine_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='createDate',
        ),
        migrations.AddField(
            model_name='storage',
            name='createDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
