# Generated by Django 2.2.7 on 2020-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20200703_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='whatsappNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='facebookPage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
