# Generated by Django 3.1.1 on 2020-09-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20200905_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='medicine',
        ),
        migrations.AddField(
            model_name='storage',
            name='medicine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
            preserve_default=False,
        ),
    ]
