# Generated by Django 3.0.7 on 2020-06-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20200624_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(upload_to='medicine/'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
