# Generated by Django 3.1.1 on 2020-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20200905_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='prices',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
