# Generated by Django 3.0.7 on 2020-06-26 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20200626_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='updateDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='createDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
