# Generated by Django 2.2.7 on 2020-08-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20200727_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='type',
        ),
    ]
