# Generated by Django 3.0.7 on 2020-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20200626_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
