# Generated by Django 3.1.1 on 2020-09-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_storage_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='prices',
        ),
    ]
