# Generated by Django 3.0.7 on 2020-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_auto_20200626_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(default='profile/profile.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
