# Generated by Django 3.1.1 on 2020-09-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_remove_storage_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='medicine.medicine'),
        ),
    ]
