# Generated by Django 3.1.1 on 2020-09-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_auto_20200905_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
    ]
