# Generated by Django 3.0.7 on 2020-06-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_auto_20200628_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='pharmacyName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
