# Generated by Django 2.2.7 on 2020-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_auto_20200803_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medcategory',
            old_name='category',
            new_name='categoryAR',
        ),
        migrations.RenameField(
            model_name='medtype',
            old_name='type',
            new_name='typeAR',
        ),
        migrations.AddField(
            model_name='medcategory',
            name='categoryEN',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medtype',
            name='typeEN',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
