# Generated by Django 3.0.7 on 2020-06-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_user_info_pharmacyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/'),
        ),
    ]
