# Generated by Django 2.2.7 on 2020-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_auto_20200803_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmedi',
            name='type',
            field=models.CharField(choices=[('request', 'طلب'), ('donate', 'تبرع')], default='request', max_length=20),
            preserve_default=False,
        ),
    ]
