# Generated by Django 3.0.7 on 2020-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_auto_20200628_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(blank=True, default='media/profile/profile.png', null=True, upload_to='medicine/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='scientificName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
