# Generated by Django 2.2.7 on 2020-09-04 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0012_requestmedi_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='facebookPage',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='img',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='pharmacyName',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='whatsappNumber',
        ),
        migrations.AddField(
            model_name='location',
            name='locUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='originCountry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='arabicName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medCategory'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufactureCompanyAr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='scientificName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medType'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='accType',
            field=models.CharField(choices=[('no', 'عادي'), ('ph', 'صيدلية'), ('or', 'مبادرة')], default='no', max_length=3),
        ),
        migrations.CreateModel(
            name='pharmacyAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyName', models.CharField(max_length=100)),
                ('facebookPage', models.URLField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('whatsappNumber', models.BigIntegerField(blank=True, null=True)),
                ('licenseImg', models.ImageField(blank=True, null=True, upload_to='license/')),
                ('licenseNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='organizationAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=100)),
                ('facebookPage', models.URLField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('whatsappNumber', models.BigIntegerField(blank=True, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
