# Generated by Django 3.1.1 on 2020-09-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_auto_20200905_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='medicine',
        ),
    ]
