# Generated by Django 3.0.7 on 2020-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_auto_20200629_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='facebookPage',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
