# Generated by Django 3.0.7 on 2020-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_user_info_facebookpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='medicine/'),
        ),
    ]
