# Generated by Django 2.2.7 on 2020-09-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_storage_dose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='dose',
        ),
    ]
