# Generated by Django 3.1.1 on 2020-09-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_remove_storage_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
            preserve_default=False,
        ),
    ]
