# Generated by Django 2.2.7 on 2020-09-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_remove_storage_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='dose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
