# Generated by Django 3.0.7 on 2020-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_auto_20200711_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmed',
            old_name='requestDate',
            new_name='request',
        ),
    ]
