# Generated by Django 2.2.7 on 2020-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_remove_storage_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(default='profile.png', upload_to='medicine/'),
        ),
        migrations.AlterField(
            model_name='pharmacyacc',
            name='licenseImg',
            field=models.ImageField(default='medicine.png', upload_to='license/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyacc',
            name='licenseNumber',
            field=models.CharField(max_length=30),
        ),
    ]
