# Generated by Django 3.0.7 on 2020-07-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_auto_20200711_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requestMed',
        ),
    ]
