# Generated by Django 2.2.7 on 2020-10-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0019_auto_20201006_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='medicine.medCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='medicine.medType'),
            preserve_default=False,
        ),
    ]
