# Generated by Django 3.0.7 on 2020-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0019_requestmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='whatsappNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='scientificName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
